const SET_STUDENT_NEW = "SET_STUDENT_NEW";
const SET_STUDENT_EXIST = "SET_STUDENT_EXIST";
const SET_STUDENT_FN = "SET_STUDENT_FN";
const SET_STUDENT_LN = "SET_STUDENT_LN";
const SET_STUDENT_ID = "SET_STUDENT_ID";
const SET_STUDENT_COURSE_CODE = "SET_STUDENT_COURSE_CODE";
const SET_STUDENT_LOGGED_IN = "SET_STUDENT_LOGGED_IN";
const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";

export {
	SET_STUDENT_NEW,
	SET_STUDENT_EXIST,
	SET_STUDENT_FN,
	SET_STUDENT_LN,
	SET_STUDENT_ID,
	SET_STUDENT_COURSE_CODE,
	SET_STUDENT_LOGGED_IN,
	ADD_NEW_STUDENT,
};
