const SET_STUDENT_NEW = "SET_STUDENT_NEW";
const SET_STUDENT_EXIST = "SET_STUDENT_EXIST";
const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";
const SET_STUDENT_FN = "SET_STUDENT_FN";
const SET_STUDENT_LN = "SET_STUDENT_LN";
const SET_STUDENT_ID = "SET_STUDENT_ID";

export {
	SET_STUDENT_NEW,
	SET_STUDENT_EXIST,
	ADD_NEW_STUDENT,
	SET_STUDENT_FN,
	SET_STUDENT_LN,
	SET_STUDENT_ID,
};
